[package]
name = "replicante_util_tracing"
version = "0.1.1"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]

description = "A collection of OpenTracing tools"
documentation = "https://docs.rs/replicante_util_tracing"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/common"
readme = "../../README.md"
keywords = ["replicante", "utility", "opentracing"]
license = "MIT"


[badges]
maintenance = { status = "actively-developed" }


[dependencies]
error-chain = "^0.12.0"
opentracingrust = "^0.3.1"
opentracingrust_zipkin = "^0.1.2"
serde = "^1.0.34"
serde_derive = "^1.0.34"
slog = "^2.2.1"


[dev-dependencies]
serde_yaml = "^0.7.3"
