[workspace]
members = [
  "logging",
  "models/agent",
  "models/api",
  "util/failure",
  "util/iron",
  "util/rndid",
  "util/tracing",
  "util/upkeep",
]

# This patch is needed to make openssl (needed by kafka) work with openssl 1.0+
[patch.crates-io]
kafka = { git = 'https://github.com/l4l/kafka-rust', branch = 'update/openssl' }
