[workspace]
members = [
  "agent/models",
  "logging",
  "util/failure",
  "util/iron",
  "util/rndid",
  "util/tracing",
]

# This patch is needed to make openssl (needed by kafka) work with openssl 1.0+
[patch.crates-io]
kafka = { git = 'https://github.com/l4l/kafka-rust', branch = 'update/openssl' }
