[package]
name = "replicante_util_iron"
version = "0.1.1"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]

description = "A collection of Iron middlewares"
documentation = "https://docs.rs/replicante_util_iron"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/common"
readme = "../../README.md"
keywords = ["replicante", "utility", "iron"]
license = "MIT"


[badges]
maintenance = { status = "actively-developed" }


[dependencies]
iron = "^0.6.0"
opentracingrust = "^0.3.1"
prometheus = "^0.4.1"
slog = "^2.2.0"


[dev-dependencies]
iron-test = "^0.6.0"
router = "^0.6.0"
