name: Rust Tests and Lints

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

# TODO: I'd like to re-add the cargo audit task but I'm not sure yet where it should be.
jobs:
  tests-and-lints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable   # Version of rust we aim to use.
          - nightly  # Preview errors early on.
          - 1.57.0   # Earliest version of rust supported.
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Prepare Cargo workspace
        run: ln -f -s Cargo.workspace.toml Cargo.toml

      - name: Build Packages
        run: cargo build

      - name: Run Tests
        run: cargo test

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt --verbose -- --check
